Try to kill slapd even if thre is not a PID_FILE.

diff --git a/src/examples/bin/local_ldap.sh.in b/src/examples/bin/local_ldap.sh.in
--- a/src/examples/bin/local_ldap.sh.in
+++ b/src/examples/bin/local_ldap.sh.in
@@ -9,6 +9,9 @@
 #****************************************************************************#
 #* $Id$
 #* $Log$
+#* Revision 1.3  2003/11/28 16:11:23  cpera
+#* Try to kill slapd even if thre is not a PID_FILE.
+#*
 #* Revision 1.2  2003/11/26 12:57:32  cpera
 #* Manage return ldapadd code "68" about data which are already registered.
 #*
@@ -64,6 +67,18 @@ ldap_stop() {
   if [ -e "$PID_FILE" ] ; then
     kill -TERM `cat $PID_FILE`
     sleep 5
+  fi
+  if [ ! -e "$PID_FILE" ] ; then
+    pprocess=`ps -wwwww -u $USER | grep sladp | grep -v -e grep | sort | head -1`
+    if [ -n "$pprocess" -a "`echo $pprocess | grep 'grep slapd'`" = "" ]; then
+      pid=`echo $pprocess | cut -f1 -d' '`
+      kill $pid > /dev/null 2>&1
+      status=$?
+      if [ $status -ne 0 ]; then
+        echo "Error: cannot stop the sladp server."
+        exit 3
+      fi
+    fi
   else
     echo "not running"
   fi
@@ -88,6 +103,13 @@ ldap_search()  { # search an entry and return the number of entries
 
 ldap_test() {
   echo "## Testing the LDAP platform ..."
+  # check slapd process
+  if [ "`ps -edfwwwww | grep slapd | grep -v -e grep`" = "" ]; then
+    echo "No sladp server seems alive."
+    exit 1
+  else
+    echo "There is a sladp server running."
+  fi
   # check server
   ldap_search dc=ens-lyon,dc=fr
   if [ $? -eq 0 ]; then
