correct cpplint issues

diff --git a/src/examples/bin/local_corba_ns.sh.in b/src/examples/bin/local_corba_ns.sh.in
--- a/src/examples/bin/local_corba_ns.sh.in
+++ b/src/examples/bin/local_corba_ns.sh.in
@@ -1,12 +1,12 @@
-#!/bin/sh
-#****************************************************************************#
+#! /bin/sh
+#* ***************************************************************************#
 #* Manager of a CORBA name server.                                          *#
 #*                                                                          *#
 #*  Author(s):                                                              *#
 #*    - Philippe COMBES (Philippe.Combes@ens-lyon.fr)                       *#
 #*                                                                          *#
 #* $LICENSE$                                                                *#
-#****************************************************************************#
+#* ***************************************************************************#
 #* $Id$
 #* $Log$
 #* Revision 1.5  2004/01/07 23:03:02  cpera
@@ -25,84 +25,103 @@
 #*
 #* Revision 1.1  2003/09/22 21:09:08  pcombes
 #* Scripts for managing a local platform with LDAP + NWS + CORBA Name server.
-#****************************************************************************#
+#* ***************************************************************************#
 
-# FIXME: this should be independent from the ORB or at least 
+# FIXME : this should be independent from the ORB or at least
 
 omni_start() {
   echo "## Starting a local CORBA name server ..."
-  processes=`ps -edfwwwww | grep -v -e grep | grep omniNames | tr '\n' '@'`
-  nb_processes=`echo $processes | tr '@' '\n' | grep omniNames | wc -l`
-  if [ "$processes" = "" -o \
-       \( "$nb_processes" -eq 1 -a "`echo $processes | grep 'grep'`" != "" \) ]
+  processes = ` ps - edfwwwww | grep - v - e grep | grep omniNames |
+              tr '\n' '@' `
+              nb_processes = ` echo $processes | tr '@' '\n' | grep omniNames |
+                             wc - l `
+                             if["$processes" = "" - o \
+                                               \ ("$nb_processes" - eq 1 -
+                                                  a
+                                                  "`echo $processes | grep 'grep'`"
+                                                  != "" \)]
+                             then
+                             if[-f $LOGDIR / omninames - ` hostname `.log \
+                                - o - f $LOGDIR / omninames - ` hostname `.bak];
   then
-    if [ -f $LOGDIR/omninames-`hostname`.log \
-         -o -f $LOGDIR/omninames-`hostname`.bak ]; then
-      $OMNINAMES -errlog $ERRLOGDIR &
+    $OMNINAMES - errlog $ERRLOGDIR &
+  else
+    $OMNINAMES - start - errlog $ERRLOGDIR &
+    fi
     else
-      $OMNINAMES -start -errlog $ERRLOGDIR &
-    fi
-  else
-    echo "Error: a CORBA name server may have already been started."
-    exit 3
-  fi
-  echo "## CORBA name server started."
-}
-
-omni_stop() {
-  echo "## Stopping the local CORBA name server ..."
-  pprocess=`ps -wwwww -u $USER | grep -v -e grep  | grep omniNames | sort | head -1`
-  if [ -n "$pprocess" -a "`echo $pprocess | grep 'grep omniNames'`" = "" ]; then
-    pid=`echo $pprocess | cut -f1 -d' '`
-    kill $pid > /dev/null 2>&1
-    status=$?
-    if [ $status -ne 0 ]; then
-      echo "Error: cannot stop the CORBA name server."
+      echo "Error: a CORBA name server may have already been started."
       exit 3
-    fi
-  fi
-  echo "## CORBA name server stopped."
-}
+      fi
+      echo "## CORBA name server started."
+      }
 
-omninames_test() {
-  if [ "`ps -edfwwwww | grep -v -e grep  | grep omniNames`" = "" ]; then
-    echo "No CORBA name server seems alive."
-  else
-    echo "There is a CORBA name server running. I cannot guess its port (normal)."
-  fi
-}
+      omni_stop() {
+        echo "## Stopping the local CORBA name server ..."
+        pprocess = ` ps - wwwww - u $USER | grep - v - e grep |
+                   grep omniNames | sort | head - 1 `
+                   if[-n "$pprocess" -
+                      a "`echo $pprocess | grep 'grep omniNames'`" = ""];
+        then
+          pid = ` echo $pprocess | cut - f1 - d ' ' `
+                kill $pid > / dev / null 2 > & 1
+                status = $ ?
+                         if[$status - ne 0];
+        then
+          echo "Error: cannot stop the CORBA name server."
+        exit 3
+        fi
+        fi
+          echo "## CORBA name server stopped."
+      }
+
+      omninames_test() {
+        if["`ps -edfwwwww | grep -v -e grep  | grep omniNames`" = ""];
+        then
+          echo "No CORBA name server seems alive."
+        else {
+          echo
+          "There is a CORBA name server running. I cannot guess its port (normal)."
+          fi
+        }
 
 
 # check shell command
-# FIXME : change command according to test results. 
-grep -v -e "grep" "$0" > /dev/null 2>&1
-if [ ! $? -ne 1 ]; then
-  echo "command \"grep -v -e\" unknown"
-  exit 3
-fi
-ps -wwwww -u $USER sshd > /dev/null 2>&1
-if [ ! $? -ne 0 ]; then
-  echo "command \"ps -wwwww -u\" unknown"
-  exit 3
-fi
+# FIXME : change command according to test results.
+        grep - v - e "grep" "$0" > / dev / null 2 > &1
+        if[!$ ? -ne 1];
+      } then
+        echo "command \"grep -v -e\" unknown"
+      exit 3
+      fi
+        ps - wwwww - u $USER sshd > / dev / null 2 > & 1
+      if[!$ ? -ne 0];
+      then
+        echo "command \"ps -wwwww -u\" unknown"
+      exit 3
+      fi
 
-if [ "`echo @OMNIORB_HOME@ | cut -c1`" != "@" ]; then
+      if["`echo @OMNIORB_HOME@ | cut -c1`" != "@"];
+      then
 
-  OMNINAMES=@OMNIORB_HOME@/bin/omniNames
-  BINDIR=`dirname $0`
-  LOGDIR=`cd $BINDIR/..; pwd`/var/log
-  ERRLOGDIR=$LOGDIR/omniNamesError.log
-  if [ ! -d $LOGDIR ]; then mkdir -p $LOGDIR; fi
-  export OMNINAMES_LOGDIR=$LOGDIR
- 
-  case "$1" in 
-    start) omni_start;;
-    stop)  omni_stop;;
-    test)  omninames_test;;
-    *) echo "$0 {start|stop|test}"; exit 3;;
-  esac
+        OMNINAMES = @OMNIORB_HOME@ / bin / omniNames
+                    BINDIR = ` dirname $0 `
+                             LOGDIR = ` cd $BINDIR /..;
+      pwd ` / var / log
+      ERRLOGDIR = $LOGDIR / omniNamesError.log
+                  if[!-d $LOGDIR];
+      then mkdir - p $LOGDIR;
+      fi
+      export OMNINAMES_LOGDIR = $LOGDIR
+
+                              case "$1" in
+                                start)omni_start;
+                                stop)omni_stop;
+                                test)omninames_test;
+                                *)echo "$0 {start|stop|test}";
+                                exit 3;
+                                esac
 
 #elif ...
-# FIXME: The code for another ORB should take place here.
+# FIXME : The code for another ORB should take place here.
 
-fi
+                                fi
diff --git a/src/examples/bin/local_ldap.sh.in b/src/examples/bin/local_ldap.sh.in
--- a/src/examples/bin/local_ldap.sh.in
+++ b/src/examples/bin/local_ldap.sh.in
@@ -1,12 +1,12 @@
-#!/bin/sh
-#****************************************************************************#
+#! /bin/sh
+#* ***************************************************************************#
 #* Manager of a local LDAP base.                                            *#
 #*                                                                          *#
 #*  Author(s):                                                              *#
 #*    - Philippe COMBES (Philippe.Combes@ens-lyon.fr)                       *#
 #*                                                                          *#
 #* $LICENSE$                                                                *#
-#****************************************************************************#
+#* ***************************************************************************#
 #* $Id$
 #* $Log$
 #* Revision 1.3  2003/11/28 16:11:23  cpera
@@ -20,189 +20,199 @@
 #*
 #* Revision 1.1  2003/09/22 21:09:08  pcombes
 #* Scripts for managing a local platform with LDAP + NWS + CORBA Name server.
-#****************************************************************************#
+#* ***************************************************************************#
 
 
 ldap_start() {
-
   echo "## Starting a local LDAP platform ..."
   echo "Start the slapd daemon on port $SLAPD_PORT."
-    
-  cmd="$SLAPD -h ldap://localhost:$SLAPD_PORT -f $SLAPD_CONF\
+
+  cmd =
+    "$SLAPD -h ldap://localhost:$SLAPD_PORT -f $SLAPD_CONF\
        > $LOGDIR/slapd.log 2>&1"
-  echo "$cmd"
-  $cmd
-  status="$?"
-  if [ "$status" -ne 0 ] ; then
+    echo "$cmd"
+    $cmd
+    status = "$?"
+             if["$status" - ne 0];
+  then
     echo "Error($status): can't start slapd. Check /var/log/debug "
-    echo "Make sure to edit $SLAPD_CONF to reflect your LDAP installation paths."
-    exit 1
+  echo "Make sure to edit $SLAPD_CONF to reflect your LDAP installation paths."
+  exit 1
   fi
   sleep 5
-  
+
   echo "Initialize the base ($BASE_LDIF)."
-  $LDAPBIN/ldapadd -x -c -H "ldap://localhost:$SLAPD_PORT"     \
-          -D "cn=admin,ou=People,dc=ens-lyon,dc=fr" -w "DUMMY_PASSWD" \
-          -f "$BASE_LDIF" >> $LOG 2>&1
-  if [ "$?" -ne 0 ] ; then
+  $LDAPBIN / ldapadd - x - c - H "ldap://localhost:$SLAPD_PORT"     \
+  - D "cn=admin,ou=People,dc=ens-lyon,dc=fr" - w "DUMMY_PASSWD" \
+  - f "$BASE_LDIF" >> $LOG 2 > & 1
+  if["$?" - ne 0];
+  then
     echo "Error: cannot add the base (check $LOG)"
-    exit 1
+  exit 1
   fi
- 
-  echo "Fill it with the plus, mult and dgemm entries ($LDIF)."
-  $LDAPBIN/ldapadd -x -c -H "ldap://localhost:$SLAPD_PORT"            \
-          -D "cn=admin,ou=People,dc=ens-lyon,dc=fr" -w "DUMMY_PASSWD" \
-	  -f "$LDIF" >> $LOG 2>&1
+
+    echo "Fill it with the plus, mult and dgemm entries ($LDIF)."
+  $LDAPBIN / ldapadd - x - c - H "ldap://localhost:$SLAPD_PORT"            \
+  - D "cn=admin,ou=People,dc=ens-lyon,dc=fr" - w "DUMMY_PASSWD" \
+  - f "$LDIF" >> $LOG 2 > & 1
   # 68 is return ldapadd code when data is already registered in ldap base ...
-  # so, it is not an error.
-  if [ "$?" -ne 0 -a "$?" -ne 68 ] ; then
+  # so , it is not an error.
+  if["$?" - ne 0 - a "$?" - ne 68];
+  then
     echo "Error: cannot add the plus, mult and dgemm problems (check $LOG)"
-    exit 1
-  fi  
-  echo "## LDAP platform started."
+  exit 1
+  fi
+    echo "## LDAP platform started."
 }
 
 ldap_stop() {
   echo "## Stopping the local LDAP platform ..."
-  if [ -e "$PID_FILE" ] ; then
-    kill -TERM `cat $PID_FILE`
-    sleep 5
+  if[-e "$PID_FILE"];
+  then
+    kill - TERM ` cat $PID_FILE `
+  sleep 5
   fi
-  if [ ! -e "$PID_FILE" ] ; then
-    pprocess=`ps -wwwww -u $USER | grep sladp | grep -v -e grep | sort | head -1`
-    if [ -n "$pprocess" -a "`echo $pprocess | grep 'grep slapd'`" = "" ]; then
-      pid=`echo $pprocess | cut -f1 -d' '`
-      kill $pid > /dev/null 2>&1
-      status=$?
-      if [ $status -ne 0 ]; then
-        echo "Error: cannot stop the sladp server."
-        exit 3
-      fi
+  if[!-e "$PID_FILE"];
+  then
+    pprocess = ` ps - wwwww - u $USER | grep sladp | grep - v - e grep | sort |
+               head - 1 `
+               if[-n "$pprocess" - a "`echo $pprocess | grep 'grep slapd'`" =
+                    ""];
+  then
+    pid = ` echo $pprocess | cut - f1 - d ' ' `
+          kill $pid > / dev / null 2 > & 1
+          status = $ ?
+                   if[$status - ne 0];
+  then
+    echo "Error: cannot stop the sladp server."
+  exit 3
+  fi
     fi
-  else
+  else {
     echo "not running"
-  fi
-
-  rm -f $PID_FILE `echo $PID_FILE | sed 's/\.pid$/args/g'` \
-         `echo $PID_FILE | sed 's/\.pid$/log/g'` $LOG
-  if [ -d $DATABASE_DIR ]; then
-    rm -rf $DATABASE_DIR/*
-  fi
-
-  echo "## LDAP platform stopped."
-}
-
-ldap_search()  { # search an entry and return the number of entries
-    count=`$LDAPBIN/ldapsearch -H ldap://localhost:$SLAPD_PORT -x -b $1\
-                    2>/dev/null | grep 'numEntries' | sed 's/# numEntries: //'`
-    if test "x$count" = "x"; then count="0"; fi
-#    affiche "$1 -> $count"
-    return $count
-}
-
-
-ldap_test() {
-  echo "## Testing the LDAP platform ..."
-  # check slapd process
-  if [ "`ps -edfwwwww | grep slapd | grep -v -e grep`" = "" ]; then
-    echo "No sladp server seems alive."
-    exit 1
-  else
-    echo "There is a sladp server running."
-  fi
-  # check server
-  ldap_search dc=ens-lyon,dc=fr
-  if [ $? -eq 0 ]; then
-     echo "slapd is not dead, but the base is empty !"
-     exit 1
-  fi
-  echo "slapd is running."
- 
-  # check content
-  err=0
-  for ldif in $LDIF ; do
-      echo "verify file $ldif"
-      for entry in `egrep '^dn:' ./$ldif |sed 's/dn: //'` ; do
-          ldap_search $entry
-          if test $? -le 0 ; then
-              err=`expr $err + 1`
-              echo "Not found in LDAP !! Entry:"
-              echo " $entry"
-          fi
-      done
-  done
-  if [ "$err" != 0 ] ; then
-      echo
-      echo "$err entrie(s) are missing."
-      exit 2
-  else
-      echo "Everything seems ok"
-  fi
-}
-
-#
-# Get the paths for slapd and ldapadd
-#
-status=0
-SLAPD="noidea"
-LDAPBIN="noidea"
-for part in `echo $PATH|sed 's|:| |g'` /sbin /usr/sbin /bin /usr/bin; do
-  if [ -x "$part/slapd" ]; then
-    if [ "x$SLAPD" = "xnoidea" ]; then
-      SLAPD="$part/slapd"
     fi
-  fi
-  if [ -x "$part/ldapadd" ]; then
-    if [ "x$LDAPBIN" = "xnoidea" ]; then
-      LDAPBIN="$part"
-    fi
-  fi
-done
-if [ "x$SLAPD" = "xnoidea" ]; then
-  echo "Cannot find the slapd binary in"
-  echo "PATH=$PATH[+:/sbin:/usr/sbin:/bin:/usr/bin]"
-  status=1
-fi
-if [ "x$LDAPBIN" = "xnoidea" ]; then
-  echo "Cannot find the LDAP binaries in"
-  echo "PATH=$PATH[+:/sbin:/usr/sbin:/bin:/usr/bin]"
-  status=1
-fi
-if [ $status -ne 0 ]; then
-  exit $status
-fi
 
-#
-# Set the configuration environment
-#
+    rm - f $PID_FILE ` echo $PID_FILE | sed 's/\.pid$/args/g' ` \
+    ` echo $PID_FILE | sed 's/\.pid$/log/g' ` $LOG
+    if[-d $DATABASE_DIR];
+  } then
+    rm - rf $DATABASE_DIR /*
+                             fi
 
-BINDIR=`dirname $0`
-PWD=`cd $BINDIR/..; pwd`
+                             echo "## LDAP platform stopped."
+                             }
 
-LOGDIR=$BINDIR/../var/log
-if [ ! -d $LOGDIR ]; then mkdir -p $LOGDIR; fi
-LOG=$LOGDIR/local_ldap.log
+                             ldap_search()  { # search an entry and return the number of entries
+                             count=`$LDAPBIN/ldapsearch -H ldap://localhost:$SLAPD_PORT -x -b $1\
+                             2>/dev/null | grep 'numEntries' | sed 's/# numEntries: //'`
+                             if test "x$count" = "x"; then count="0"; fi
+                           #    affiche "$1 -> $count"
+                             return $count
+                             }
 
-CONFDIR=$BINDIR/../etc
-LDIF=$CONFDIR/plus_mult_dgemm.ldif
-BASE_LDIF=$CONFDIR/base.ldif
 
-SLAPD_CONF=$CONFDIR/slapd.cfg
-SLAPD_PORT=9050
+                             ldap_test() {
+                             echo "## Testing the LDAP platform ..."
+                           # check slapd process
+                             if [ "`ps -edfwwwww | grep slapd | grep -v -e grep`" = "" ]; then
+                             echo "No sladp server seems alive."
+                             exit 1
+                             else
+                             echo "There is a sladp server running."
+                             fi
+                           # check server
+                             ldap_search dc=ens-lyon,dc=fr
+                             if [ $? -eq 0 ]; then
+                             echo "slapd is not dead, but the base is empty !"
+                             exit 1
+                             fi
+                             echo "slapd is running."
 
-DATABASE_DIR=`grep ^directory $SLAPD_CONF`
-DATABASE_DIR=`echo $DATABASE_DIR | cut -f2- -d' '`
-if [ ! -d $DATABASE_DIR ]; then
-  mkdir -p $DATABASE_DIR
-fi
+                           # check content
+                             err=0
+                             for ldif in $LDIF ; do
+                             echo "verify file $ldif"
+                             for entry in `egrep '^dn:' ./$ldif |sed 's/dn: //'` ; do
+                             ldap_search $entry
+                             if test $? -le 0 ; then
+                             err=`expr $err + 1`
+                             echo "Not found in LDAP !! Entry:"
+                             echo " $entry"
+                             fi
+                             done
+                             done
+                             if [ "$err" != 0 ] ; then
+                             echo
+                             echo "$err entrie(s) are missing."
+                             exit 2
+                             else
+                             echo "Everything seems ok"
+                             fi
+                             }
 
-PID_FILE=`grep ^pidfile $SLAPD_CONF`
-PID_FILE=`echo $PID_FILE | cut -f2- -d' '`
+                           #
+                           # Get the paths for slapd and ldapadd
+                           #
+                             status=0
+                             SLAPD="noidea"
+                             LDAPBIN="noidea"
+                             for part in `echo $PATH|sed 's|:| |g'` /sbin /usr/sbin /bin /usr/bin; do
+                             if [ -x "$part/slapd" ]; then
+                             if [ "x$SLAPD" = "xnoidea" ]; then
+                             SLAPD="$part/slapd"
+                             fi
+                             fi
+                             if [ -x "$part/ldapadd" ]; then
+                             if [ "x$LDAPBIN" = "xnoidea" ]; then
+                             LDAPBIN="$part"
+                             fi
+                             fi
+                             done
+                             if [ "x$SLAPD" = "xnoidea" ]; then
+                             echo "Cannot find the slapd binary in"
+                             echo "PATH=$PATH[+:/sbin:/usr/sbin:/bin:/usr/bin]"
+                             status=1
+                             fi
+                             if [ "x$LDAPBIN" = "xnoidea" ]; then
+                             echo "Cannot find the LDAP binaries in"
+                             echo "PATH=$PATH[+:/sbin:/usr/sbin:/bin:/usr/bin]"
+                             status=1
+                             fi
+                             if [ $status -ne 0 ]; then
+                             exit $status
+                             fi
 
-case "$1" in 
-  start) ldap_start;;
-  stop)  ldap_stop;;
-  test)  ldap_test;;
-  *) echo "$0 {start|stop|test} (and not $1)"; exit 1;;
-esac
+                           #
+                           # Set the configuration environment
+                           #
+
+                             BINDIR=`dirname $0`
+                             PWD=`cd $BINDIR/..; pwd`
+
+                             LOGDIR=$BINDIR/../var/log
+                             if [ ! -d $LOGDIR ]; then mkdir -p $LOGDIR; fi
+                             LOG=$LOGDIR/local_ldap.log
+
+                             CONFDIR=$BINDIR/../etc
+                             LDIF=$CONFDIR/plus_mult_dgemm.ldif
+                             BASE_LDIF=$CONFDIR/base.ldif
+
+                             SLAPD_CONF=$CONFDIR/slapd.cfg
+                             SLAPD_PORT=9050
+
+                             DATABASE_DIR=`grep ^directory $SLAPD_CONF`
+                             DATABASE_DIR=`echo $DATABASE_DIR | cut -f2- -d' '`
+                             if [ ! -d $DATABASE_DIR ]; then
+                             mkdir -p $DATABASE_DIR
+                             fi
+
+                             PID_FILE=`grep ^pidfile $SLAPD_CONF`
+                             PID_FILE=`echo $PID_FILE | cut -f2- -d' '`
+
+                             case "$1" in
+                             start) ldap_start;;
+                             stop)  ldap_stop;;
+                             test)  ldap_test;;
+                           #*) echo "$0 {start|stop|test} (and not $1)"; exit 1;;
+                             esac
 
diff --git a/src/examples/bin/local_platform.sh.in b/src/examples/bin/local_platform.sh.in
--- a/src/examples/bin/local_platform.sh.in
+++ b/src/examples/bin/local_platform.sh.in
@@ -1,5 +1,5 @@
-#!/bin/sh
-#****************************************************************************#
+#! /bin/sh
+#* ***************************************************************************#
 #* Manager of a local platform, containing:                                 *#
 #*   - an LDAP base                                                         *#
 #*   - an NWS platform:                                                     *#
@@ -10,7 +10,7 @@
 #*    - Philippe COMBES (Philippe.Combes@ens-lyon.fr)                       *#
 #*                                                                          *#
 #* $LICENSE$                                                                *#
-#****************************************************************************#
+#* ***************************************************************************#
 #* $Id$
 #* $Log$
 #* Revision 1.1  2003/09/26 14:05:39  pcombes
@@ -18,38 +18,46 @@
 #*
 #* Revision 1.1  2003/09/22 21:09:08  pcombes
 #* Scripts for managing a local platform with LDAP + NWS + CORBA Name server.
-#****************************************************************************#
+#* ***************************************************************************#
 
-mode=$1
+mode = $1
 
-case "$mode" in
- restart)
-   $0 stop && echo && $0 start;;
- stop)
-   mode=${mode}p;;
- start|test);;
- *) echo "$0 {start|stop|restart|test}"; exit 1;;
-esac
-status=$?
-if [ "$status" -ne 0 -o "$mode" = "restart" ]; then
-  exit $status
-fi
+     case "$mode" in
+       restart)
+       $0 stop && echo && $0 start;
+       stop)
+       mode = $ {mode} p;
+       start | test);
+       *)echo "$0 {start|stop|restart|test}";
+       exit 1;
+       esac
+         status = $ ?
+                  if["$status" - ne 0 - o "$mode" = "restart"];
+       then
+       exit $status
+       fi
 
-BINDIR=`dirname $0`
+         BINDIR = ` dirname $0 `
 
-$BINDIR/local_ldap.sh     $1 &&\
-$BINDIR/local_nws.sh      $1 &&\
-$BINDIR/local_corba_ns.sh $1
-status=$?
+                  $BINDIR / local_ldap.sh $1 && \
+                  $BINDIR / local_nws.sh $1 && \
+                  $BINDIR / local_corba_ns.sh $1
+                  status = $ ?
 
-case $status in
-  0) echo "The local FAST platform has been successfully ${mode}ed.";;
-  1) echo "The local LDAP base could not be ${mode}ed.";;
-  2) echo "The local NWS platform could not be ${mode}ed.";;
-  3) echo "The local CORBA name server could not be ${mode}ed.";;
-  *) echo "I am not sure that the local platform has been successfully ${mode}ed,"
-     echo " probably because of the CORBA name server. Just try, and if it does"
-     echo " not work, try changing its listening port, or killing all CORBA name"
-     echo " servers running.";;
-esac
-exit $status
+                         case $status in
+                           0)echo
+                           "The local FAST platform has been successfully ${mode}ed.";
+                           1)echo "The local LDAP base could not be ${mode}ed.";
+                           2)echo
+                           "The local NWS platform could not be ${mode}ed.";
+                           3)echo
+                           "The local CORBA name server could not be ${mode}ed.";
+                           *)echo
+                           "I am not sure that the local platform has been successfully ${mode}ed,"
+                           echo
+                           " probably because of the CORBA name server. Just try, and if it does"
+                           echo
+                           " not work, try changing its listening port, or killing all CORBA name"
+                           echo " servers running.";
+                           esac
+                           exit $status
